openapi: 3.0.3
info:
  title: Laravel
  description: 'Client List API Docs'
  version: 1.0.0
servers:
  -
    url: 'http://localhost:4500'
paths:
  /v1/clients:
    get:
      summary: 'Display a listing of the clients.'
      description: ''
      parameters:
        -
          in: query
          name: page_size
          description: 'Size per page. Defaults to 20.'
          example: 11
          required: false
          schema:
            type: integer
            description: 'Size per page. Defaults to 20.'
            example: 11
        -
          in: query
          name: page
          description: 'int Page to view.'
          example: 4
          required: false
          schema:
            type: integer
            description: 'int Page to view.'
            example: 4
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: '0'
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: ''
                      email: null
                      title: null
                      first_name: null
                      last_name: null
                      primary_phone: null
                      secondary_phone: null
                      avatar: null
                      job_title: null
                      timezone: null
                      company_id: null
                      user: null
                    -
                      id: ''
                      email: null
                      title: null
                      first_name: null
                      last_name: null
                      primary_phone: null
                      secondary_phone: null
                      avatar: null
                      job_title: null
                      timezone: null
                      company_id: null
                      user: null
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: ''
                        email: null
                        title: null
                        first_name: null
                        last_name: null
                        primary_phone: null
                        secondary_phone: null
                        avatar: null
                        job_title: null
                        timezone: null
                        company_id: null
                        user: null
                      -
                        id: ''
                        email: null
                        title: null
                        first_name: null
                        last_name: null
                        primary_phone: null
                        secondary_phone: null
                        avatar: null
                        job_title: null
                        timezone: null
                        company_id: null
                        user: null
                    items:
                      type: object
      tags:
        - 'Client Management'
      security: []
    post:
      summary: 'Store a newly created client in storage.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: '0'
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: ''
                    email: null
                    title: null
                    first_name: null
                    last_name: null
                    primary_phone: null
                    secondary_phone: null
                    avatar: null
                    job_title: null
                    timezone: null
                    company_id: null
                    user: null
                properties:
                  data:
                    type: object
                    example:
                      id: ''
                      email: null
                      title: null
                      first_name: null
                      last_name: null
                      primary_phone: null
                      secondary_phone: null
                      avatar: null
                      job_title: null
                      timezone: null
                      company_id: null
                      user: null
      tags:
        - 'Client Management'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: marc.carter@example.org
                first_name:
                  type: string
                  description: ''
                  example: possimus
                last_name:
                  type: string
                  description: ''
                  example: porro
                avatar:
                  type: string
                  description: 'Must be a valid URL.'
                  example: 'http://www.cremin.com/quidem-voluptatem-in-cupiditate-officia-a'
                title:
                  type: string
                  description: ''
                  example: sunt
                primary_phone:
                  type: string
                  description: ''
                  example: ex
                secondary_phone:
                  type: string
                  description: ''
                  example: debitis
                job_title:
                  type: string
                  description: ''
                  example: voluptate
                timezone:
                  type: string
                  description: ''
                  example: aspernatur
                company_id:
                  type: string
                  description: ''
                  example: doloremque
                user_id:
                  type: string
                  description: ''
                  example: dolore
              required:
                - email
                - first_name
                - user_id
      security: []
  /v1/clients/create:
    get:
      summary: 'Show the form for creating a new client.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: '0'
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: ''
                    email: null
                    title: null
                    first_name: null
                    last_name: null
                    primary_phone: null
                    secondary_phone: null
                    avatar: null
                    job_title: null
                    timezone: null
                    company_id: null
                    user: null
                properties:
                  data:
                    type: object
                    example:
                      id: ''
                      email: null
                      title: null
                      first_name: null
                      last_name: null
                      primary_phone: null
                      secondary_phone: null
                      avatar: null
                      job_title: null
                      timezone: null
                      company_id: null
                      user: null
      tags:
        - 'Client Management'
      security: []
  '/v1/clients/{id}':
    get:
      summary: 'Display the specified client.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: '0'
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: ''
                    email: null
                    title: null
                    first_name: null
                    last_name: null
                    primary_phone: null
                    secondary_phone: null
                    avatar: null
                    job_title: null
                    timezone: null
                    company_id: null
                    user: null
                properties:
                  data:
                    type: object
                    example:
                      id: ''
                      email: null
                      title: null
                      first_name: null
                      last_name: null
                      primary_phone: null
                      secondary_phone: null
                      avatar: null
                      job_title: null
                      timezone: null
                      company_id: null
                      user: null
      tags:
        - 'Client Management'
      security: []
    put:
      summary: 'Update the specified client in storage.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: '0'
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: ''
                    email: null
                    title: null
                    first_name: null
                    last_name: null
                    primary_phone: null
                    secondary_phone: null
                    avatar: null
                    job_title: null
                    timezone: null
                    company_id: null
                    user: null
                properties:
                  data:
                    type: object
                    example:
                      id: ''
                      email: null
                      title: null
                      first_name: null
                      last_name: null
                      primary_phone: null
                      secondary_phone: null
                      avatar: null
                      job_title: null
                      timezone: null
                      company_id: null
                      user: null
      tags:
        - 'Client Management'
      security: []
    delete:
      summary: 'Remove the specified client from storage.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: '0'
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: ''
                    email: null
                    title: null
                    first_name: null
                    last_name: null
                    primary_phone: null
                    secondary_phone: null
                    avatar: null
                    job_title: null
                    timezone: null
                    company_id: null
                    user: null
                properties:
                  data:
                    type: object
                    example:
                      id: ''
                      email: null
                      title: null
                      first_name: null
                      last_name: null
                      primary_phone: null
                      secondary_phone: null
                      avatar: null
                      job_title: null
                      timezone: null
                      company_id: null
                      user: null
      tags:
        - 'Client Management'
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the client.'
        example: 16
        required: true
        schema:
          type: integer
  '/v1/clients/{client_id}/edit':
    get:
      summary: 'Show the form for editing the specified client.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: '0'
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: ''
                    email: null
                    title: null
                    first_name: null
                    last_name: null
                    primary_phone: null
                    secondary_phone: null
                    avatar: null
                    job_title: null
                    timezone: null
                    company_id: null
                    user: null
                properties:
                  data:
                    type: object
                    example:
                      id: ''
                      email: null
                      title: null
                      first_name: null
                      last_name: null
                      primary_phone: null
                      secondary_phone: null
                      avatar: null
                      job_title: null
                      timezone: null
                      company_id: null
                      user: null
      tags:
        - 'Client Management'
      security: []
    parameters:
      -
        in: path
        name: client_id
        description: 'The ID of the client.'
        example: 5
        required: true
        schema:
          type: integer
  /v1/companies:
    get:
      summary: 'Display a listing of the companies.'
      description: ''
      parameters:
        -
          in: query
          name: page_size
          description: 'Size per page. Defaults to 20.'
          example: 7
          required: false
          schema:
            type: integer
            description: 'Size per page. Defaults to 20.'
            example: 7
        -
          in: query
          name: page
          description: 'int Page to view.'
          example: 18
          required: false
          schema:
            type: integer
            description: 'int Page to view.'
            example: 18
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: '0'
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: ''
                      name: null
                      logo: null
                      email: null
                      domain: null
                      description: null
                      primary_phone: null
                      secondary_phone: null
                      address: null
                      user: null
                    -
                      id: ''
                      name: null
                      logo: null
                      email: null
                      domain: null
                      description: null
                      primary_phone: null
                      secondary_phone: null
                      address: null
                      user: null
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: ''
                        name: null
                        logo: null
                        email: null
                        domain: null
                        description: null
                        primary_phone: null
                        secondary_phone: null
                        address: null
                        user: null
                      -
                        id: ''
                        name: null
                        logo: null
                        email: null
                        domain: null
                        description: null
                        primary_phone: null
                        secondary_phone: null
                        address: null
                        user: null
                    items:
                      type: object
      tags:
        - 'Company Mangement'
      security: []
    post:
      summary: 'Store a newly created company in storage.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: '0'
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: ''
                    name: null
                    logo: null
                    email: null
                    domain: null
                    description: null
                    primary_phone: null
                    secondary_phone: null
                    address: null
                    user: null
                properties:
                  data:
                    type: object
                    example:
                      id: ''
                      name: null
                      logo: null
                      email: null
                      domain: null
                      description: null
                      primary_phone: null
                      secondary_phone: null
                      address: null
                      user: null
      tags:
        - 'Company Mangement'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: temporibus
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: jlynch@example.com
                domain:
                  type: string
                  description: ''
                  example: earum
                primary_phone:
                  type: string
                  description: ''
                  example: necessitatibus
                secondary_phone:
                  type: string
                  description: ''
                  example: ab
                address:
                  type: string
                  description: ''
                  example: sint
                description:
                  type: string
                  description: ''
                  example: maiores
                logo:
                  type: string
                  description: ''
                  example: blanditiis
                user_id:
                  type: string
                  description: ''
                  example: aut
                client_ids:
                  type: array
                  description: ''
                  example:
                    - odio
                  items:
                    type: string
              required:
                - user_id
      security: []
  /v1/companies/create:
    get:
      summary: 'Show the form for creating a new company.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: '0'
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: ''
                    name: null
                    logo: null
                    email: null
                    domain: null
                    description: null
                    primary_phone: null
                    secondary_phone: null
                    address: null
                    user: null
                properties:
                  data:
                    type: object
                    example:
                      id: ''
                      name: null
                      logo: null
                      email: null
                      domain: null
                      description: null
                      primary_phone: null
                      secondary_phone: null
                      address: null
                      user: null
      tags:
        - 'Company Mangement'
      security: []
  '/v1/companies/{id}':
    get:
      summary: 'Display the specified company.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: '0'
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: ''
                    name: null
                    logo: null
                    email: null
                    domain: null
                    description: null
                    primary_phone: null
                    secondary_phone: null
                    address: null
                    user: null
                properties:
                  data:
                    type: object
                    example:
                      id: ''
                      name: null
                      logo: null
                      email: null
                      domain: null
                      description: null
                      primary_phone: null
                      secondary_phone: null
                      address: null
                      user: null
      tags:
        - 'Company Mangement'
      security: []
    put:
      summary: 'Update the specified company in storage.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: '0'
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: ''
                    name: null
                    logo: null
                    email: null
                    domain: null
                    description: null
                    primary_phone: null
                    secondary_phone: null
                    address: null
                    user: null
                properties:
                  data:
                    type: object
                    example:
                      id: ''
                      name: null
                      logo: null
                      email: null
                      domain: null
                      description: null
                      primary_phone: null
                      secondary_phone: null
                      address: null
                      user: null
      tags:
        - 'Company Mangement'
      security: []
    delete:
      summary: 'Remove the specified company from storage.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: '0'
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: ''
                    name: null
                    logo: null
                    email: null
                    domain: null
                    description: null
                    primary_phone: null
                    secondary_phone: null
                    address: null
                    user: null
                properties:
                  data:
                    type: object
                    example:
                      id: ''
                      name: null
                      logo: null
                      email: null
                      domain: null
                      description: null
                      primary_phone: null
                      secondary_phone: null
                      address: null
                      user: null
      tags:
        - 'Company Mangement'
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the company.'
        example: 17
        required: true
        schema:
          type: integer
  '/v1/companies/{company_id}/edit':
    get:
      summary: 'Show the form for editing the specified company.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: '0'
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: ''
                    name: null
                    logo: null
                    email: null
                    domain: null
                    description: null
                    primary_phone: null
                    secondary_phone: null
                    address: null
                    user: null
                properties:
                  data:
                    type: object
                    example:
                      id: ''
                      name: null
                      logo: null
                      email: null
                      domain: null
                      description: null
                      primary_phone: null
                      secondary_phone: null
                      address: null
                      user: null
      tags:
        - 'Company Mangement'
      security: []
    parameters:
      -
        in: path
        name: company_id
        description: 'The ID of the company.'
        example: 11
        required: true
        schema:
          type: integer
  /v1/user:
    get:
      summary: 'Display authenticated user.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: '0'
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: null
                    uuid: 7aaff904-c007-3e54-be40-3205f99e863c
                properties:
                  data:
                    type: object
                    example:
                      id: null
                      uuid: 7aaff904-c007-3e54-be40-3205f99e863c
      tags:
        - 'User Management'
      security: []
    delete:
      summary: 'Remove the specified user from storage.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: '0'
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: null
                    uuid: c731efea-1aa4-3f82-a46f-f3763c86935b
                properties:
                  data:
                    type: object
                    example:
                      id: null
                      uuid: c731efea-1aa4-3f82-a46f-f3763c86935b
      tags:
        - 'User Management'
      security: []
tags:
  -
    name: 'Client Management'
    description: "\nAPI to manage the client resource."
  -
    name: 'Company Mangement'
    description: "\nAPI to manage company resource."
  -
    name: 'User Management'
    description: "\nAPI to manage the user resource."
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
